/*
 *  Copyright 2012 Owexz.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

package net.owexz.PaintedStone;
 
import java.util.logging.Logger;

import org.bukkit.plugin.java.JavaPlugin;
import org.getspout.spoutapi.SpoutManager;
import org.getspout.spoutapi.block.design.Texture;
import org.getspout.spoutapi.inventory.*;
import org.getspout.spoutapi.material.CustomBlock;
import org.getspout.spoutapi.material.MaterialData;
 
 
public class PaintedStone extends JavaPlugin
{
 
    public PaintedStone()
    {
        log = Logger.getLogger("Minecraft");
        BlackStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/5578079.png", 64, 16, 16);
        BlueStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/1864681.png", 64, 16, 16);
        BrownStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/9251445.png", 64, 16, 16);
        CyanStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/4248659.png", 64, 16, 16);
        GreenStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/3464522.png", 64, 16, 16);
        LightBlueStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/6757814.png", 64, 16, 16);
        LimeStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7239441.png", 64, 16, 16);
        MagentaStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7694621.png", 64, 16, 16);
        OrangeStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7151376.png", 64, 16, 16);
        PinkStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7831939.png", 64, 16, 16);
        PurpleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/9137035.png", 64, 16, 16);
        RedStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/6750918.png", 64, 16, 16);
        WhiteStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/6338613.png", 64, 16, 16);
        YellowStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/3983204.png", 64, 16, 16);
        BlackCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7326876.png", 64, 16, 16);
        BlueCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/9661142.png", 64, 16, 16);
        BrownCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7944579.png", 64, 16, 16);
        CyanCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/5241324.png", 64, 16, 16);
        GreenCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/9064429.png", 64, 16, 16);
        LightBlueCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/3289060.png", 64, 16, 16);
        LimeCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/8019113.png", 64, 16, 16);
        MagentaCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/1755093.png", 64, 16, 16);
        OrangeCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/1749389.png", 64, 16, 16);
        PinkCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/3134081.png", 64, 16, 16);
        PurpleCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7871224.png", 64, 16, 16);
        RedCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/6802317.png", 64, 16, 16);
        WhiteCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/8102036.png", 64, 16, 16);
        YellowCobbleStoneBlockTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7461858.png", 64, 16, 16);
        BlackGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/1848050.png", 64, 16, 16);
        BlueGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/1566440.png", 64, 16, 16);
        BrownGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/7601325.png", 64, 16, 16);
        CyanGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/433511.png", 64, 16, 16);
        GreenGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/958177.png", 64, 16, 16);
        LightBlueGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/5379460.png", 64, 16, 16);
        LimeGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/9737367.png", 64, 16, 16);
        MagentaGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/4986010.png", 64, 16, 16);
        OrangeGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/6847302.png", 64, 16, 16);
        PinkGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/8835567.png", 64, 16, 16);
        PurpleGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/5511379.png", 64, 16, 16);
        RedGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/5395357.png", 64, 16, 16);
        WhiteGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/4709953.png", 64, 16, 16);
        YellowGlowstoneTexture = new Texture(this, "http://www.jamoscraft.owexz.net/uploads/1/4/8/5/1485487/6592614.png", 64, 16, 16);
    }
 
    public void onEnable()
    {
    	BlackStoneBlock = new BlackStoneBlock(this);
    	BlueStoneBlock = new BlueStoneBlock(this);
    	BrownStoneBlock = new BrownStoneBlock(this);
    	CyanStoneBlock = new CyanStoneBlock(this);
    	GreenStoneBlock = new GreenStoneBlock(this);
    	LightBlueStoneBlock = new LightBlueStoneBlock(this);
    	LimeStoneBlock = new LimeStoneBlock(this);
    	MagentaStoneBlock = new MagentaStoneBlock(this);
    	OrangeStoneBlock = new OrangeStoneBlock(this);
    	PinkStoneBlock = new PinkStoneBlock(this);
    	PurpleStoneBlock = new PurpleStoneBlock(this);
    	RedStoneBlock = new RedStoneBlock(this);
    	WhiteStoneBlock = new WhiteStoneBlock(this);
    	YellowStoneBlock = new YellowStoneBlock(this);
    	BlackCobbleStoneBlock = new BlackCobbleStoneBlock(this);
    	BlueCobbleStoneBlock = new BlueCobbleStoneBlock(this);
    	BrownCobbleStoneBlock = new BrownCobbleStoneBlock(this);
    	CyanCobbleStoneBlock = new CyanCobbleStoneBlock(this);
    	GreenCobbleStoneBlock = new GreenCobbleStoneBlock(this);
    	LightBlueCobbleStoneBlock = new LightBlueCobbleStoneBlock(this);
    	LimeCobbleStoneBlock = new LimeCobbleStoneBlock(this);
    	MagentaCobbleStoneBlock = new MagentaCobbleStoneBlock(this);
    	OrangeCobbleStoneBlock = new OrangeCobbleStoneBlock(this);
    	PinkCobbleStoneBlock = new PinkCobbleStoneBlock(this);
    	PurpleCobbleStoneBlock = new PurpleCobbleStoneBlock(this);
    	RedCobbleStoneBlock = new RedCobbleStoneBlock(this);
    	WhiteCobbleStoneBlock = new WhiteCobbleStoneBlock(this);
    	YellowCobbleStoneBlock = new YellowCobbleStoneBlock(this);
    	BlackGlowstone = new BlackGlowstone(this);
    	BlueGlowstone = new BlueGlowstone(this);
    	BrownGlowstone = new BrownGlowstone(this);
    	CyanGlowstone = new CyanGlowstone(this);
    	GreenGlowstone = new GreenGlowstone(this);
    	LightBlueGlowstone = new LightBlueGlowstone(this);
    	LimeGlowstone = new LimeGlowstone(this);
    	MagentaGlowstone = new MagentaGlowstone(this);
    	OrangeGlowstone = new OrangeGlowstone(this);
    	PinkGlowstone = new PinkGlowstone(this);
    	PurpleGlowstone = new PurpleGlowstone(this);
    	RedGlowstone = new RedGlowstone(this);
    	WhiteGlowstone = new WhiteGlowstone(this);
    	YellowGlowstone = new YellowGlowstone(this);
        SpoutShapedRecipe recipe = new SpoutShapedRecipe(new SpoutItemStack(BlackStoneBlock, 2));
        recipe.shape("   ", "ABA", "   ");
        recipe.setIngredient('A', MaterialData.stone);
        recipe.setIngredient('B', MaterialData.inkSac);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe);
        SpoutShapedRecipe recipe1 = new SpoutShapedRecipe(new SpoutItemStack(BlueStoneBlock, 2));
        recipe1.shape("   ", "ABA", "   ");
        recipe1.setIngredient('A', MaterialData.stone);
        recipe1.setIngredient('B', MaterialData.lapisLazuli);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe1);
        SpoutShapedRecipe recipe2 = new SpoutShapedRecipe(new SpoutItemStack(BrownStoneBlock, 2));
        recipe2.shape("   ", "ABA", "   ");
        recipe2.setIngredient('A', MaterialData.stone);
        recipe2.setIngredient('B', MaterialData.cocoaBeans);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe2);
        SpoutShapedRecipe recipe3 = new SpoutShapedRecipe(new SpoutItemStack(CyanStoneBlock, 2));
        recipe3.shape("   ", "ABA", "   ");
        recipe3.setIngredient('A', MaterialData.stone);
        recipe3.setIngredient('B', MaterialData.cyanDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe3);
        SpoutShapedRecipe recipe4 = new SpoutShapedRecipe(new SpoutItemStack(GreenStoneBlock, 2));
        recipe4.shape("   ", "ABA", "   ");
        recipe4.setIngredient('A', MaterialData.stone);
        recipe4.setIngredient('B', MaterialData.cactusGreen);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe4);
        SpoutShapedRecipe recipe5 = new SpoutShapedRecipe(new SpoutItemStack(LightBlueStoneBlock, 2));
        recipe5.shape("   ", "ABA", "   ");
        recipe5.setIngredient('A', MaterialData.stone);
        recipe5.setIngredient('B', MaterialData.lightBlueDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe5);
        SpoutShapedRecipe recipe6 = new SpoutShapedRecipe(new SpoutItemStack(LimeStoneBlock, 2));
        recipe6.shape("   ", "ABA", "   ");
        recipe6.setIngredient('A', MaterialData.stone);
        recipe6.setIngredient('B', MaterialData.limeDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe6);
        SpoutShapedRecipe recipe7 = new SpoutShapedRecipe(new SpoutItemStack(MagentaStoneBlock, 2));
        recipe7.shape("   ", "ABA", "   ");
        recipe7.setIngredient('A', MaterialData.stone);
        recipe7.setIngredient('B', MaterialData.magentaDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe7);
        SpoutShapedRecipe recipe8 = new SpoutShapedRecipe(new SpoutItemStack(OrangeStoneBlock, 2));
        recipe8.shape("   ", "ABA", "   ");
        recipe8.setIngredient('A', MaterialData.stone);
        recipe8.setIngredient('B', MaterialData.orangeDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe8);
        SpoutShapedRecipe recipe9 = new SpoutShapedRecipe(new SpoutItemStack(PinkStoneBlock, 2));
        recipe9.shape("   ", "ABA", "   ");
        recipe9.setIngredient('A', MaterialData.stone);
        recipe9.setIngredient('B', MaterialData.pinkDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe9);
        SpoutShapedRecipe recipe10 = new SpoutShapedRecipe(new SpoutItemStack(PurpleStoneBlock, 2));
        recipe10.shape("   ", "ABA", "   ");
        recipe10.setIngredient('A', MaterialData.stone);
        recipe10.setIngredient('B', MaterialData.purpleDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe10);
        SpoutShapedRecipe recipe11 = new SpoutShapedRecipe(new SpoutItemStack(RedStoneBlock, 2));
        recipe11.shape("   ", "ABA", "   ");
        recipe11.setIngredient('A', MaterialData.stone);
        recipe11.setIngredient('B', MaterialData.roseRed);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe11);
        SpoutShapedRecipe recipe12 = new SpoutShapedRecipe(new SpoutItemStack(WhiteStoneBlock, 2));
        recipe12.shape("   ", "ABA", "   ");
        recipe12.setIngredient('A', MaterialData.stone);
        recipe12.setIngredient('B', MaterialData.boneMeal);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe12);
        SpoutShapedRecipe recipe13 = new SpoutShapedRecipe(new SpoutItemStack(YellowStoneBlock, 2));
        recipe13.shape("   ", "ABA", "   ");
        recipe13.setIngredient('A', MaterialData.stone);
        recipe13.setIngredient('B', MaterialData.dandelionYellow);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe13);
        SpoutShapedRecipe recipe14 = new SpoutShapedRecipe(new SpoutItemStack(BlackCobbleStoneBlock, 2));
        recipe14.shape("   ", "ABA", "   ");
        recipe14.setIngredient('A', MaterialData.cobblestone);
        recipe14.setIngredient('B', MaterialData.inkSac);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe14);
        SpoutShapedRecipe recipe15 = new SpoutShapedRecipe(new SpoutItemStack(BlueCobbleStoneBlock, 2));
        recipe15.shape("   ", "ABA", "   ");
        recipe15.setIngredient('A', MaterialData.cobblestone);
        recipe15.setIngredient('B', MaterialData.lapisLazuli);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe15);
        SpoutShapedRecipe recipe16 = new SpoutShapedRecipe(new SpoutItemStack(BrownCobbleStoneBlock, 2));
        recipe16.shape("   ", "ABA", "   ");
        recipe16.setIngredient('A', MaterialData.cobblestone);
        recipe16.setIngredient('B', MaterialData.cocoaBeans);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe16);
        SpoutShapedRecipe recipe17 = new SpoutShapedRecipe(new SpoutItemStack(CyanCobbleStoneBlock, 2));
        recipe17.shape("   ", "ABA", "   ");
        recipe17.setIngredient('A', MaterialData.cobblestone);
        recipe17.setIngredient('B', MaterialData.cyanDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe17);
        SpoutShapedRecipe recipe18 = new SpoutShapedRecipe(new SpoutItemStack(GreenCobbleStoneBlock, 2));
        recipe18.shape("   ", "ABA", "   ");
        recipe18.setIngredient('A', MaterialData.cobblestone);
        recipe18.setIngredient('B', MaterialData.cactusGreen);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe18);
        SpoutShapedRecipe recipe19 = new SpoutShapedRecipe(new SpoutItemStack(LightBlueCobbleStoneBlock, 2));
        recipe19.shape("   ", "ABA", "   ");
        recipe19.setIngredient('A', MaterialData.cobblestone);
        recipe19.setIngredient('B', MaterialData.lightBlueDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe19);
        SpoutShapedRecipe recipe20 = new SpoutShapedRecipe(new SpoutItemStack(LimeCobbleStoneBlock, 2));
        recipe20.shape("   ", "ABA", "   ");
        recipe20.setIngredient('A', MaterialData.cobblestone);
        recipe20.setIngredient('B', MaterialData.limeDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe20);
        SpoutShapedRecipe recipe21 = new SpoutShapedRecipe(new SpoutItemStack(MagentaCobbleStoneBlock, 2));
        recipe21.shape("   ", "ABA", "   ");
        recipe21.setIngredient('A', MaterialData.cobblestone);
        recipe21.setIngredient('B', MaterialData.magentaDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe21);
        SpoutShapedRecipe recipe22 = new SpoutShapedRecipe(new SpoutItemStack(OrangeCobbleStoneBlock, 2));
        recipe22.shape("   ", "ABA", "   ");
        recipe22.setIngredient('A', MaterialData.cobblestone);
        recipe22.setIngredient('B', MaterialData.orangeDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe22);
        SpoutShapedRecipe recipe23 = new SpoutShapedRecipe(new SpoutItemStack(PinkCobbleStoneBlock, 2));
        recipe23.shape("   ", "ABA", "   ");
        recipe23.setIngredient('A', MaterialData.cobblestone);
        recipe23.setIngredient('B', MaterialData.pinkDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe9);
        SpoutShapedRecipe recipe24 = new SpoutShapedRecipe(new SpoutItemStack(PurpleCobbleStoneBlock, 2));
        recipe24.shape("   ", "ABA", "   ");
        recipe24.setIngredient('A', MaterialData.cobblestone);
        recipe24.setIngredient('B', MaterialData.purpleDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe24);
        SpoutShapedRecipe recipe25 = new SpoutShapedRecipe(new SpoutItemStack(RedCobbleStoneBlock, 2));
        recipe25.shape("   ", "ABA", "   ");
        recipe25.setIngredient('A', MaterialData.cobblestone);
        recipe25.setIngredient('B', MaterialData.roseRed);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe25);
        SpoutShapedRecipe recipe26 = new SpoutShapedRecipe(new SpoutItemStack(WhiteCobbleStoneBlock, 2));
        recipe26.shape("   ", "ABA", "   ");
        recipe26.setIngredient('A', MaterialData.cobblestone);
        recipe26.setIngredient('B', MaterialData.boneMeal);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe26);
        SpoutShapedRecipe recipe27 = new SpoutShapedRecipe(new SpoutItemStack(YellowCobbleStoneBlock, 2));
        recipe27.shape("   ", "ABA", "   ");
        recipe27.setIngredient('A', MaterialData.cobblestone);
        recipe27.setIngredient('B', MaterialData.dandelionYellow);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe27);
        SpoutShapedRecipe recipe28 = new SpoutShapedRecipe(new SpoutItemStack(BlackGlowstone, 2));
        recipe28.shape("   ", "ABA", "   ");
        recipe28.setIngredient('A', MaterialData.glowstoneBlock);
        recipe28.setIngredient('B', MaterialData.inkSac);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe28);
        SpoutShapedRecipe recipe29 = new SpoutShapedRecipe(new SpoutItemStack(BlueGlowstone, 2));
        recipe29.shape("   ", "ABA", "   ");
        recipe29.setIngredient('A', MaterialData.glowstoneBlock);
        recipe29.setIngredient('B', MaterialData.lapisLazuli);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe29);
        SpoutShapedRecipe recipe30 = new SpoutShapedRecipe(new SpoutItemStack(BrownGlowstone, 2));
        recipe30.shape("   ", "ABA", "   ");
        recipe30.setIngredient('A', MaterialData.glowstoneBlock);
        recipe30.setIngredient('B', MaterialData.cocoaBeans);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe30);
        SpoutShapedRecipe recipe31 = new SpoutShapedRecipe(new SpoutItemStack(CyanGlowstone, 2));
        recipe31.shape("   ", "ABA", "   ");
        recipe31.setIngredient('A', MaterialData.glowstoneBlock);
        recipe31.setIngredient('B', MaterialData.cyanDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe31);
        SpoutShapedRecipe recipe32 = new SpoutShapedRecipe(new SpoutItemStack(GreenGlowstone, 2));
        recipe32.shape("   ", "ABA", "   ");
        recipe32.setIngredient('A', MaterialData.glowstoneBlock);
        recipe32.setIngredient('B', MaterialData.cactusGreen);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe32);
        SpoutShapedRecipe recipe33 = new SpoutShapedRecipe(new SpoutItemStack(LightBlueGlowstone, 2));
        recipe33.shape("   ", "ABA", "   ");
        recipe33.setIngredient('A', MaterialData.glowstoneBlock);
        recipe33.setIngredient('B', MaterialData.lightBlueDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe33);
        SpoutShapedRecipe recipe34 = new SpoutShapedRecipe(new SpoutItemStack(LimeGlowstone, 2));
        recipe34.shape("   ", "ABA", "   ");
        recipe34.setIngredient('A', MaterialData.glowstoneBlock);
        recipe34.setIngredient('B', MaterialData.limeDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe34);
        SpoutShapedRecipe recipe35 = new SpoutShapedRecipe(new SpoutItemStack(MagentaGlowstone, 2));
        recipe35.shape("   ", "ABA", "   ");
        recipe35.setIngredient('A', MaterialData.glowstoneBlock);
        recipe35.setIngredient('B', MaterialData.magentaDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe21);
        SpoutShapedRecipe recipe36 = new SpoutShapedRecipe(new SpoutItemStack(OrangeGlowstone, 2));
        recipe36.shape("   ", "ABA", "   ");
        recipe36.setIngredient('A', MaterialData.glowstoneBlock);
        recipe36.setIngredient('B', MaterialData.orangeDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe36);
        SpoutShapedRecipe recipe37 = new SpoutShapedRecipe(new SpoutItemStack(PinkGlowstone, 2));
        recipe37.shape("   ", "ABA", "   ");
        recipe37.setIngredient('A', MaterialData.glowstoneBlock);
        recipe37.setIngredient('B', MaterialData.pinkDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe37);
        SpoutShapedRecipe recipe38 = new SpoutShapedRecipe(new SpoutItemStack(PurpleGlowstone, 2));
        recipe38.shape("   ", "ABA", "   ");
        recipe38.setIngredient('A', MaterialData.glowstoneBlock);
        recipe38.setIngredient('B', MaterialData.purpleDye);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe38);
        SpoutShapedRecipe recipe39 = new SpoutShapedRecipe(new SpoutItemStack(RedGlowstone, 2));
        recipe39.shape("   ", "ABA", "   ");
        recipe39.setIngredient('A', MaterialData.glowstoneBlock);
        recipe39.setIngredient('B', MaterialData.roseRed);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe39);
        SpoutShapedRecipe recipe40 = new SpoutShapedRecipe(new SpoutItemStack(WhiteGlowstone, 2));
        recipe40.shape("   ", "ABA", "   ");
        recipe40.setIngredient('A', MaterialData.glowstoneBlock);
        recipe40.setIngredient('B', MaterialData.boneMeal);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe40);
        SpoutShapedRecipe recipe41 = new SpoutShapedRecipe(new SpoutItemStack(YellowGlowstone, 2));
        recipe41.shape("   ", "ABA", "   ");
        recipe41.setIngredient('A', MaterialData.glowstoneBlock);
        recipe41.setIngredient('B', MaterialData.dandelionYellow);
        SpoutManager.getMaterialManager().registerSpoutRecipe(recipe41);
        log.info("PaintedStone by Owexz (Owexz.net) Enabled");
    }
 
    public void onDisable()
    {
        log.info("PaintedStone by Owexz (Owexz.net) disabled.");
    }
 
    public static CustomBlock BlackStoneBlock;
    CustomBlock BlueStoneBlock;
    CustomBlock BrownStoneBlock;
    CustomBlock CyanStoneBlock;
    CustomBlock GreenStoneBlock;
    CustomBlock LightBlueStoneBlock;
    CustomBlock LimeStoneBlock;
    CustomBlock MagentaStoneBlock;
    CustomBlock OrangeStoneBlock;
    CustomBlock PinkStoneBlock;
    CustomBlock PurpleStoneBlock;
    CustomBlock RedStoneBlock;
    CustomBlock WhiteStoneBlock;
    CustomBlock YellowStoneBlock;
    CustomBlock BlackCobbleStoneBlock;
    CustomBlock BlueCobbleStoneBlock;
    CustomBlock BrownCobbleStoneBlock;
    CustomBlock CyanCobbleStoneBlock;
    CustomBlock GreenCobbleStoneBlock;
    CustomBlock LightBlueCobbleStoneBlock;
    CustomBlock LimeCobbleStoneBlock;
    CustomBlock MagentaCobbleStoneBlock;
    CustomBlock OrangeCobbleStoneBlock;
    CustomBlock PinkCobbleStoneBlock;
    CustomBlock PurpleCobbleStoneBlock;
    CustomBlock RedCobbleStoneBlock;
    CustomBlock WhiteCobbleStoneBlock;
    CustomBlock YellowCobbleStoneBlock;
    CustomBlock BlackGlowstone;
    CustomBlock BlueGlowstone;
    CustomBlock BrownGlowstone;
    CustomBlock CyanGlowstone;
    CustomBlock GreenGlowstone;
    CustomBlock LightBlueGlowstone;
    CustomBlock LimeGlowstone;
    CustomBlock MagentaGlowstone;
    CustomBlock OrangeGlowstone;
    CustomBlock PinkGlowstone;
    CustomBlock PurpleGlowstone;
    CustomBlock RedGlowstone;
    CustomBlock WhiteGlowstone;
    CustomBlock YellowGlowstone;
    Logger log;
    public Texture BlackStoneBlockTexture;
    Texture BlueStoneBlockTexture;
    Texture BrownStoneBlockTexture;
    Texture CyanStoneBlockTexture;
    Texture GreenStoneBlockTexture;
    Texture LightBlueStoneBlockTexture;
    Texture LimeStoneBlockTexture;
    Texture MagentaStoneBlockTexture;
    Texture OrangeStoneBlockTexture;
    Texture PinkStoneBlockTexture;
    Texture PurpleStoneBlockTexture;
    Texture RedStoneBlockTexture;
    Texture WhiteStoneBlockTexture;
    Texture YellowStoneBlockTexture;
    Texture BlackCobbleStoneBlockTexture;
    Texture BlueCobbleStoneBlockTexture;
    Texture BrownCobbleStoneBlockTexture;
    Texture CyanCobbleStoneBlockTexture;
    Texture GreenCobbleStoneBlockTexture;
    Texture LightBlueCobbleStoneBlockTexture;
    Texture LimeCobbleStoneBlockTexture;
    Texture MagentaCobbleStoneBlockTexture;
    Texture OrangeCobbleStoneBlockTexture;
    Texture PinkCobbleStoneBlockTexture;
    Texture PurpleCobbleStoneBlockTexture;
    Texture RedCobbleStoneBlockTexture;
    Texture WhiteCobbleStoneBlockTexture;
    Texture YellowCobbleStoneBlockTexture;
    Texture BlackGlowstoneTexture;
    Texture BlueGlowstoneTexture;
    Texture BrownGlowstoneTexture;
    Texture CyanGlowstoneTexture;
    Texture GreenGlowstoneTexture;
    Texture LightBlueGlowstoneTexture;
    Texture LimeGlowstoneTexture;
    Texture MagentaGlowstoneTexture;
    Texture OrangeGlowstoneTexture;
    Texture PinkGlowstoneTexture;
    Texture PurpleGlowstoneTexture;
    Texture RedGlowstoneTexture;
    Texture WhiteGlowstoneTexture;
    Texture YellowGlowstoneTexture;
    
    
}